name: API Testing

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API server
        run: |
          nohup python main.py &

      - name: Wait for API to be ready
        run: sleep 5

      - name: Run API tests
        run: pytest tests/

      - name: Stop API server
        run: pkill -f main.py
