name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: check code
      uses: actions/checkout@v3

    - name: login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-api:latest .

    - name: push Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-api:latest
